language: ruby
rvm:
- 2.2.2
node_js:
  - "4.1.2"
#cache: yarn
cache:
   directories:
     - node_modules
#env:
#  global:
#    - TRAVIS_NODE_VERSION="6.9.5"
install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm
  - (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`)
  - source ~/.nvm/nvm.sh
  - nvm install "4.1.2"
  - bundle install
  - npm install
  - npm run install-all
script:
  - npm run lint
  - bundle exec jekyll build
cache: bundler
notifications:
  email: false
sudo: false
after_success:
  - npm install aerobatic-cli -g
  - aero deploy \
    --commit-url "https://github.com/itsuporte/itsuporte.github.io/commit/${TRAVIS_COMMIT}" \
    --directory _site
