matrix:
  include:

      - language: ruby
        rvm:
        - 2.3.3

        before_script:
         - chmod +x ./script/cibuild # or do this locally and commit

        # Assume bundler is being used, therefore
        # the `install` step will run `bundle install` by default.
        script: ./script/cibuild

        # branch whitelist, only for GitHub Pages
        branches:
          only:
          - master # test the master branch

        env:
          global:
          - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
          - TRAVIS_NODE_VERSION="6.9.5"

        sudo: false # route your build to the container-based infrastructure for a faster build

        script:
          - bundle exec jekyll build

        install:
          - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm
          - (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`)
          - source ~/.nvm/nvm.sh
          - nvm install $TRAVIS_NODE_VERSION
          - bundle install --path vendor/bundle
          - npm install

        after_success:
          - npm install aerobatic-cli -g
          - aero deploy --force
            --directory _site

        #BITBALLOON 
      - language: node_js
        node_js:
        - '0.11'
        before_install:
        - travis_retry gem install bitballoon
        script: node_modules/punch/bin/punch g
        after_success: bitballoon deploy output --access-token=$BB_ACCESS_TOKEN --site-id=$BB_SITE_ID
        branches:
          only:
            - master
