language: ruby
rvm:
- 2.3.3

before_script:
 - chmod +x ./script/cibuild # or do this locally and commit

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: ./script/cibuild

# branch whitelist, only for GitHub Pages
branches:
  only:
  - master # test the master branch
  
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
  - TRAVIS_NODE_VERSION="9.11.1"

sudo: false # route your build to the container-based infrastructure for a faster build

script:
  - bundle exec jekyll build

install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm
  - (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`)
  - source ~/.nvm/nvm.sh
  - nvm install $TRAVIS_NODE_VERSION
  - bundle install --path vendor/bundle
  - npm install

after_success:
  - npm install aerobatic-cli -g
  - aero deploy --force
    --directory _site
  - npm install -g firebase-tools
  - firebase 
  - firebase --project webupdates target:apply hosting webip itsuporte
  - firebase deploy --only hosting --token=${FIREBASE_API_TOKEN}
