language: 
 - ruby
 - node_js
 
rvm:
- 2.3.3

# branch whitelist, only for GitHub Pages
branches:
  only:
  - master # test the master branch

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
  - TRAVIS_NODE_VERSION="9.11.1"

sudo: false # route your build to the container-based infrastructure for a faster build

before_script:
 - chmod +x ./script/cibuild # or do this locally and commit

script:
# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
 - ./script/cibuild
 - bundle exec jekyll build
  
before_install:
- openssl aes-256-cbc -k "$super_secret_password" -in serviceAccount.json.enc -out serviceAccount.json -d

install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm
  - (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`)
  - source ~/.nvm/nvm.sh
  - nvm install $TRAVIS_NODE_VERSION
  - bundle install --path vendor/bundle
  - npm install

after_success:
  - npm install aerobatic-cli -g
  - aero deploy --force
    --directory _site
  - npm install -g firebase-tools
  - npm install -g firebase-import
  - firebase 
  - firebase target:apply hosting webip itsuporte
  - firebase deploy --only hosting:webip --token=${FIREBASE_API_TOKEN}
  - firebase-import --database_url ${fb_database_url} --path / --json ./json/progdiv-source.json --service_account ./serviceAccount.json --force

node_js:
  - "node"

deploy:
  provider: surge
  project: ./
  domain: https://itsuporte.surge.sh
