sudo: false
language: ruby
rvm: 2.2
env:
  global:
    - TRAVIS_NODE_VERSION="6.9.5"
install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm
  - (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`)
  - source ~/.nvm/nvm.sh
  - nvm install $TRAVIS_NODE_VERSION
  - bundle install
  - npm install
script:
  - bundle exec jekyll build
after_success:
  - npm install aerobatic-cli -g
  - aero deploy \
    --commit-url "https://github.com/itsuporte/itsuporte.github.io/commit/${TRAVIS_COMMIT}" \
    --directory _site
