safe: false
lsi: false
pygments: true

relative_source: /
destination: /

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
username: itsuporte
repo: itsuporte.github.io
branch: master

permalink: pretty

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - vendor
  - .travis.yml
