pipelines:
  branches:
    master:
      - step:
          script:
          - bundle install                 # Run bundler against the Gemfile
          - bundle exec jekyll build       # Build the site
          - npm install -g aerobatic-cli   # Install the aero CLI
          - aero deploy --directory /      # Deploy the built site to Aerobatic
