pipelines:
  branches:
    master:
      - step:
          script:
          - npm install -g aerobatic-cli   # Install the aero CLI
          - aero deploy --directory /      # Deploy the built site to Aerobatic
