#!/usr/bin/env bash
set -e # halt script on error

bundle exec jekyll build
#bundle exec htmlproofer ./_site --disable-external

#Neocities
var NeoCities = require('neocities')
var api = new NeoCities('NEOUSERNAME', 'NEOPASSWORD')
npm install neocities --global

#Hexo
npm install hexo-cli -g
hexo init
npm install
#hexo server

#Neocities & Hexo
npm install -save hexo-deployer-neocities
hexo deploy
