#!/usr/bin/env bash
set -e # halt script on error

bundle exec jekyll build
#bundle exec htmlproofer ./_site --disable-external

#Neocities
npm install -g hexo-cli
npm install --save hexo-deployer-neocities
hexo deploy
